### ISSUE TITLE
Retroactive GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#102]
We need to decide how we will calculate retroactive GIVbacks after the economy launchs...
- when is the cut off date
- where those tokens will come from

**Comment by laurenluz** [comment]
for donors from March until launch... we should just use rGIV and then announce it later... cut this from scope of launch to have sanity.

**Comment by laurenluz** [comment]
will be good to do after price stabiliizes

**Comment by GriffGreen** [comment]
Yeah! 

I would say that, just like the rest of the GIVeconomy, this should be a GIVstream game... part liquid and the rest streaming.

Also I wouldn't do it straight across the board... 
Donations to Giveth get 100% GIVbacks 
Donations to Verified projects (if they are verified at the time of the retroGIVbacks get 75% GIVbacks
Donations to listed projects get 10% GIVbacks (more like early beta tester benefits), but we look to make sure that any BIG winner in this group look legit... and weren't circulating donations.

**Comment by laurenluz** [comment]
Love this! Where do the funds come from? rGIV? or will we make a proposal in the GIVgarden?

@WhyldWanderer when did we start verifying projects? Do you have a specific date for tracking?

**Comment by WhyldWanderer** [comment]
This first application was submitted April 7th, 2021. The first Verification Party was held Arpil 9,2021. I don't know the exact date that the first badge was given though as it was a manual process at that time. 
According to this [issue](https://github.com/Giveth/giveth-next/issues/85) it seems like it was June 15, 2021.

**Comment by laurenluz** [comment]
nice! Thanks!

**Comment by laurenluz** [comment]
With our current script can put in the dates June to December 24... 
Review list - for fraud, for correct prices
Can try to distribute betweens round 2 and 3...
work on comms on this
will run the script with price of giv at time of running script... review for fraud and then run again and disribute

will get tokens from rDAO

**Comment by GriffGreen** [comment]
I would say that we look at any verified projects that are verified NOW and then we need to scan Trace and Giveth.io starting on Feb 28th 2021 (any time, there were no donations that day... at least on Trace) to Dec 24th, 2021 10am 

There will be a lot of recirculating donations probably... especially from the Commons Stack :facepalm: so we will probably take some time to review so many months of donations.

**Comment by laurenluz** [comment]
@divine-comedian can you help to run the script on this and get the data? or @mohammadranjbarz ?

We want all donations from Feb 28, 2021 11:59pm Costa Rica time to Devember 24, 2021 10am Costa Rica time... and it would be great to separate/sort the list in three groups:
- donations to Giveth (our TRACE campaign or project on io)
- donations to verified projects (using the list of projects that are verified *today*)
- donations to all other projects

Since it will take time to go through the list, would be nice to get the list this week sometime.

**Comment by mohammadranjbarz** [comment]
> @divine-comedian can you help to run the script on this and get the data? or @mohammadranjbarz ?
> 
> We want all donations from Feb 28, 2021 11:59pm Costa Rica time to Devember 24, 2021 10am Costa Rica time... and it would be great to separate/sort the list in three groups:
> 
> * donations to Giveth (our TRACE campaign or project on io)
> * donations to verified projects (using the list of projects that are verified _today_)
> * donations to all other projects
> 
> Since it will take time to go through the list, would be nice to get the list this week sometime.

@divine-comedian  You already can get first two items, for third one I should do some changes

**Comment by divine-comedian** [comment]
@mohammadranjbarz  no problem getting verified project donations and donations to Giveth - looks like we're missing some more information to properly sort trace donations -

![image](https://user-images.githubusercontent.com/67759413/150529224-97ed58a3-2e8f-443c-a0b1-b222cae05176.png)

we'll need some way to check which donations were made  to the giveth campaign - https://trace.giveth.io/campaign/giveth-2

**Comment by divine-comedian** [comment]
@laurenluz  work started in our data review file for GIVbacks 
https://docs.google.com/spreadsheets/d/1iJvE5QCd4wXXd-_2tr4x8H0zgqDGMN0yVMub72EPn48/edit?usp=sharing

you can see some new tabs for retroactive GIVbacks. We'll still need to filter out donations to giveth via TRACE as well as donations to non-verified projects (minus verified projects)

**Comment by laurenluz** [comment]
@MoeNick would love to add this to mohammad for the next sprint

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/GIVeconomy/102?planning-poker) with ZenHub @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@MoeNick 

I implement an endpoitn `/not-eligible-donations` in givback-calculation project, so if you call that, you will get 
The donations of purple list givers of giveth.io/giveth trace + donations to unverified projects(campaigns/trace) in giveth trace
And I added the name of entity that has been donated to( for giveth trace donations)
Is it enough?

**PS** As I would go to trip in few hours and I'm not available till weekend, I didn't merge the PR, I want to check it witch @laurenluz  or @divine-comedian  before merging that

**Comment by divine-comedian** [comment]
I think this should be fine but we need to verify if purple list donors would be eligible for GIVbacks or not. we'll need to modify the endpoint based on this. or perhaps a new endpoint that is donations to non-verified projects minus purple list donations. 

let's check in with @thegriff and @laurenluz

**Comment by mohammadranjbarz** [comment]
- [ ] The donations of purple list givers of giveth.io/giveth trace + donations to unverified projects(campaigns/trace) in giveth trace
- [ ] Add names of trace givers in script output
- [ ] donations to non-verified  projects(in giveth.io? ) minus purple list donation


@divine-comedian  I think there are lots of comments, maybe it's better to make it clear, do you can check this checklist to see of it's enough or not

**Comment by divine-comedian** [comment]
@mohammadranjbarz  I just checked in with griff and co. We can include donations to non-verified projects, including purple list donations.

**Comment by mohammadranjbarz** [comment]
@divine-comedian  @WhyldWanderer 

Now we have to endpoints for getting donations:
1. https://givback.develop.giveth.io/api-docs/#/default/get_eligible_donations Return all donations to verified projects/campaigns and purple List addresses are excluded

2. https://givback.develop.giveth.io/api-docs/#/default/get_not_eligible_donations Return all donations to unVerified projects/campaigns and donations to verified projects/campains from purple list addresses

Please review it and we can move it done if you think it's ok

**Comment by divine-comedian** [comment]
@mohammadranjbarz  wow your API work is amazing! 

I test out `not_eligible_donations` and `eligible_donations` the information produced in the CSV file came out clear. very nice work!

One small change would be when I download the not_eligible_donations csv file the default file name is `purple-list-donations...` maybe we change this to `not-eligible-donations...` to match the name of the endpoint?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz wow your API work is amazing!
> 
> I test out `not_eligible_donations` and `eligible_donations` the information produced in the CSV file came out clear. very nice work!
> 
> One small change would be when I download the not_eligible_donations csv file the default file name is `purple-list-donations...` maybe we change this to `not-eligible-donations...` to match the name of the endpoint?

Nice catch, I fixed the name of downloadd file

<img width="1436" alt="Screen Shot 1400-12-06 at 21 53 35" src="https://user-images.githubusercontent.com/9850545/155767843-1f3e8d26-cd4c-4d5b-bb1d-d547e20ddbc0.png">

ُاشدنس

**Comment by divine-comedian** [comment]
forum post is up - https://forum.giveth.io/t/retroactive-givbacks/412 
We'll look for advice and keep the community updated on the review and distribution process via this thread.
