### ISSUE TITLE
[P2] - Deprecating the GIVgarden

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#900]
As per https://forum.giveth.io/t/ending-the-givgarden/1320 we should deprecate the GIVgarden 

- [x] Create a new multisig which will only hold the GIVgarden funds and disburse future proposal funding
- [x] Create a transaction from the giveth main multisig transferring the GIVgarden’s GIVstream to the new multisig
- [x] Create a vote from the GIVgarden which will:
- [x] pause the voting apps on the GIVgarden (prevent more proposals and prevent voting on proposals)
- [x] Send all of the GIV it holds to the new multisig

- [ ] Giveth/giveth-dapps-v2#3799
- [x] Giveth/giveth-docs#201
- [x] (?) Notify the community via Discord (?)
- [x] Edit the covenent (it says all kinds of stuff about using Gardens & Celeste… we need to agree on what our new dispute process will be with the snapshot)

## Considerations 

Check out proposal processes & documentations of other DAOs using snapshot for this because, as you mentioned, I think we don’t have a lot of an appetite for willy-nilly funding

Clearly define the parameters of the snapshot & new gov processes & make a new forum post about it (explaining/defining what is required to post a proposal [rGIV?], etc.)

Clearly communicate this with our community - maybe it’s worth it also from a DAO-education perspective to make a blog post or explainer about the evolution of giveth governance and why we’re stopping to use CV.

**Comment by oyealmond** [comment]
Should I move this to the Notion as an epic? Or this is part of Giveth development @divine-comedian?

**Comment by divine-comedian** [comment]
> Should I move this to the Notion as an epic? Or this is part of Giveth development @divine-comedian?

this is development

**Comment by jainkrati** [comment]
@MoeNick pls confirm if there are any other issues pending for this epic but not linked here.
